[package]
name = "hello-world"
version = "0.1.0"
authors = ["rouxcaesar <jrzerwick@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "hello"
path = "src/hello.rs"
